version: '3.8'

services:
  web:
    build: ./loginapp
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./loginapp/:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  
  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=dbadmin1234
      - POSTGRES_DB=user_db

volumes:
  postgres_data: