# Generated by Django 5.0.6 on 2024-06-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StandardUser',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=250)),
                ('emailid', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
            ],
        ),
    ]
